package in.ibm.chirra.saf.enums;

public enum REPORT {
	
	ADD_STEP_TO_REPORT_TRUE,
	ADD_STEP_TO_REPORT_FALSE,
	
	ADD_STEP_TO_REPORT_WITHSCREENSHOT_TRUE,
	ADD_STEP_TO_REPORT_WITHSCREENSHOT_FALSE
	
}
